name: catweb
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ui
  flutter_rating_bar: ^4.0.1
  flutter_linkify: ^6.0.0
  flutter_highlight: ^0.7.0
  cupertino_icons: ^1.0.8
  flutter_swipe_action_cell: ^3.1.4
  extended_image: ^8.2.1
  cupertino_modal_sheet: ^1.1.0
  bot_toast: ^4.1.3
  scrollable_positioned_list: ^0.3.8
  photo_view: ^0.14.0

  pull_to_refresh:
    git: https://github.com/miquelbeltran/flutter_pulltorefresh

  # network
  brotli: ^0.6.0
  dio: ^5.4.2+1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_db_store: ^5.1.1
  dio_smart_retry: ^6.0.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  dio_http_formatter: ^3.2.1

  flutter_inappwebview: ^5.8.0
  webview_cookie_manager: ^2.0.6

  # state
  flutter_hooks: ^0.20.5
  get_it: ^7.6.4
  provider: ^6.1.2


  # database
  drift: ^2.14.1
  shared_preferences: ^2.2.2
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3

  # tools
  intl: ^0.19.0
  synchronized: ^3.1.0+1
  uuid: ^4.0.0
  rxdart: ^0.27.7
  logger: ^2.0.2+1
  yaml: ^3.1.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  collection: ^1.18.0

  # parser
  # catweb_parser:
  #   path: ../catweb_parser_go



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  drift_dev: ^2.14.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  custom_lint: ^0.5.7



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/