name: catweb
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ui
  flutter_speed_dial: ^5.0.0
  flutter_rating_bar: ^4.0.0
  flutter_linkify: ^5.0.2
  flutter_highlight: ^0.7.0
  cupertino_icons: ^1.0.4
  flutter_sticky_header: ^0.6.0
  flutter_swipe_action_cell: ^2.1.4
  pull_to_refresh: ^2.0.0
  extended_image: ^6.0.1
  modal_bottom_sheet: ^2.0.1
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master

  # network
  brotli: ^0.5.0
  dio: ^4.0.4
  dio_cache_interceptor: ^3.2.6
  dio_cache_interceptor_db_store: ^4.1.1
  dio_http_formatter:
    git:
      url: git@github.com:simonkimi/dio_http_formatter.git

  # state
  get: ^4.3.8
  flutter_hooks: ^0.18.0

  # database
  drift: ^1.3.0
  shared_preferences: ^2.0.9
  sqlite3_flutter_libs: ^0.5.3
  path_provider: ^2.0.0
  path: ^1.8.0

  # tools
  protobuf: ^2.0.0
  intl: ^0.17.0
  synchronized: ^3.0.0
  uuid: ^3.0.5
  tuple: ^2.0.0

  # parser
  catweb_parser:
    git:
      url: git@github.com:simonkimi/catweb-parser.git


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  drift_dev: ^1.1.0
  dart_code_metrics: ^4.12.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/