name: catweb
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ui
  flutter_speed_dial: ^5.0.0
  flutter_rating_bar: ^4.0.0
  flutter_linkify: ^5.0.2
  bot_toast: ^4.0.1
  flutter_highlight: ^0.7.0
  cupertino_icons: ^1.0.4
  flutter_sticky_header: ^0.6.0
  flutter_swipe_action_cell: ^2.1.4
  pull_to_refresh: ^2.0.0
  extended_sliver: ^2.0.1

  # network
  brotli: ^0.5.0
  dio: ^4.0.4
  dio_cache_interceptor: ^3.0.3
  dio_http_formatter: ^2.1.0
  dio_cache_interceptor_db_store: ^4.1.1

  # state
  get: ^4.3.8
  flutter_hooks: ^0.18.0

  # database
  drift: ^1.3.0
  shared_preferences: ^2.0.9
  sqlite3_flutter_libs: ^0.5.3
  path_provider: ^2.0.0
  path: ^1.8.0

  # tools
  protobuf: ^2.0.0
  intl: ^0.17.0
  synchronized: ^3.0.0
  uuid: ^3.0.5
  ffi: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  drift_dev: ^1.1.0
  ffigen: ^4.1.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/

ffigen:
  output: 'lib/gen/h/libgo.h.dart'
  headers:
    entry-points:
      - 'lib/libs/libgo.h'